CREATE OR REPLACE TABLE ELT_DB.ELT_SCHEMA.EMPLOYEE 
(
ID VARCHAR(10),
NAME VARCHAR(20),
ADDRESS VARCHAR(40),
START_DATE DATE,
END_DATE DATE

)
COMMENT = "THIS IS SAMPLE EMPLOYEE TABLE BEING USED FOR DEMONSTRATING SCD TYPE 2 IMPLEMENTATION";